[package]
name = "baides"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0.1"
hmac-sha256 = "1.1.2"
base64 = "0.13.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
